#!/usr/bin/env bash
# Gives info about my domain & subdomain

call_dig() {
dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print "The subdomain " subdomain " is a " $4 " record and points to " $5}' subdomain="$2"
}

if [ "$#"];
then
call_dig "$1" "www"
call_dig "$2" "lb_01"
call_dif "$3" "web_01"
call_dig "$4" "web_02"
elif [ "$#" == 2 ];
then
call_dig "$1" "$2"
fi
