#!/usr/bin/env bash
# Configure Nginx on a new Ubuntu machine to add a custom HTTP response header

# Update the system and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Configure Nginx to add the custom header
sudo sed -i "/server_name _;/a \\\tadd_header X-Served-By \$HOSTNAME\;" /etc/nginx/sites-available/default

# Create sample HTML files
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Restart Nginx to apply changes
sudo service nginx restart
