#!/usr/bin/env bash
# Check if the password argument is provided
mysqldump -u root --password=$1 --all-databases > backup.sql

DATE_FORMAT=$(date +"%d-%m-%Y")

tar -czvf "$DATE_FORMAT.tar.gz" backup.sql
