#!/usr/bin/env bash
#Edit the hosts file on your style

sudo echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
sudo echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

# Restart networking to apply changes
sudo systemctl restart networking
