#!/usr/bin/env bash
# limiting everything by the permissions of the nginx user
# Stop nginx service if already running
service nginx stop

# Ensure nginx user exists
useradd -r nginx

# Update nginx configuration to run as nginx user
sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf

# Update nginx configuration to listen on all active IPs on port 8080
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default

# Restart nginx service to apply changes
service nginx start
