#!/usr/bin/env bash
# limiting everything by the permissions of the nginx user and it should listen to all active IPs on port 8080
# Stop nginx service if already running
pkill apache
# Update nginx configuration to listen on all active IPs on port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo service nginx stop
echo 'user nginx;'>> /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
