#!/usr/bin/env bash
# limiting everything by the permissions of the nginx user and it should listen to all active IPs on port 8080
# Stop nginx service if already running
pkill apache
# Update nginx configuration to listen on all active IPs on port 8080
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default
sudo service nginx stop

# Update nginx configuration to run as nginx user
echo 'user nginx;'>> /etc/nginx/nginx.conf
# nginx.conf file is readable by both the nginx user and group, but only writable by the nginx user
chmod 644 /etc/nginx/nginx.conf

# Restart nginx service to apply changes
sudo -u nginx service nginx start
