#!/usr/bin/env bash
# limiting everything by the permissions of the nginx user and it should listen to all active IPs on port 8080
pkill apache
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i 's/# user www-data/user nginx/g' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
