#!/usr/bin/env bash

# Specify the key name
KEY_NAME="school"

# Generate RSA key pair with 4096 bits
ssh-keygen -t rsa -b 4096 -f ~/.ssh/$KEY_NAME

# Add passphrase to the private key
ssh-keygen -f ~/.ssh/$KEY_NAME -N "betty"

